include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-ffp-backbone-wifi

include $(TOPDIR)/../package/gluon.mk

define Package/gluon-ffp-backbone-wifi
  TITLE:=Provides connection to the Freifunk Potsdam 5GHz Backbone network
  DEPENDS:=+gluon-core
endef

$(eval $(call BuildPackageGluon,gluon-ffp-backbone-wifi))
