#!/usr/bin/lua

local site = require 'gluon.site'
local file = '/etc/dropbear/authorized_keys'

local keys = {}

local function load_keys()
	for line in io.lines(file) do
		keys[line] = true
	end
end

pcall(load_keys)

local f = io.open(file, 'a')
for _, key in ipairs(site.authorized_keys()) do
	if not keys[key] and not keys['#' .. key] then
		if keys['#'] then
			f:write('#' .. key .. '\n')
		else
			f:write(key .. '\n')
		end
	end
end
f:close()
