include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-cf-ew72-wifi5fix

include $(TOPDIR)/../package/gluon.mk

define Package/gluon-cf-ew72-wifi5fix
  TITLE:=Fix 5GHz Wifi on Comfast EW-72 by increasing channes width to 40 MHz
  DEPENDS:=+gluon-core
endef

$(eval $(call BuildPackageGluon,gluon-cf-ew72-wifi5fix))
