#!/usr/bin/lua

local json = require 'jsonc'
local uci = require('simple-uci').cursor()
local board_data = json.load('/etc/board.json')
local network_data = (board_data or {}).network

local devs = {}
for _,i in ipairs( uci:get("network","wan","ifname") ) do
    if i ~= network_data.wan.device and i ~= network_data.lan.device then
        table.insert(devs,i)
    end
end
uci:set("network","global","extra_devs_wan",devs)

local devs = {}
for _,i in ipairs( uci:get("network","client","ifname") ) do
    if i ~= network_data.wan.device and i ~= network_data.lan.device then
        table.insert(devs,i)
    end
end
uci:set("network","global","extra_devs_client",devs)

uci:commit("network")
