#!/usr/bin/lua

local json = require 'jsonc'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()
local board_data = json.load('/etc/board.json')
local network_data = (board_data or {}).network

local devs = uci:get_list('network', 'wan', 'ifname')
local olddevs = uci:get_list('network_gluon-old','wan','ifname')
if olddevs then
    for _,i in ipairs( olddevs ) do
        if string.match(i,"eth%d+") and i ~= network_data.wan.device and i ~= network_data.lan.device then
            util.add_to_set(devs, i)
        end
    end
    uci:set_list('network', 'wan', 'ifname', devs)
end

local devs = uci:get_list('network', 'client', 'ifname')
local olddevs = uci:get_list('network_gluon-old','wan','ifname')
if olddevs then
    for _,i in ipairs( olddevs ) do
        if string.match(i,"eth%d+") and i ~= network_data.wan.device and i ~= network_data.lan.device then
            util.add_to_set(devs, i)
        end
    end
    uci:set_list('network', 'client', 'ifname', devs)
end

uci:commit("network")
