#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

local devs = uci:get_list('network', 'wan', 'ifname')
local extra = uci:get('network','globals','extra_devs_wan')
if extra then
    for _,i in ipairs( extra ) do
        util.add_to_set(devs, i)
    end
    uci:set_list('network', 'wan', 'ifname', devs)
    uci:delete('network','globals','extra_devs_wan')
end

local devs = uci:get_list('network', 'client', 'ifname')
local extra = uci:get('network','globals','extra_devs_client')
if extra then
    for _,i in ipairs( extra ) do
        util.add_to_set(devs, i)
    end
    uci:set_list('network', 'client', 'ifname', devs)
    uci:delete('network','globals','extra_devs_client')
end

uci:commit("network")
